development:
  adapter: postgresql
  encoding: utf8
  database: rspec_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: rspec_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: rspec_production
  pool: 5
  password:
